### ISSUE TITLE
炫酷

### ISSUE THREAD

**Issue by kainy** [MartinDelophy/vocal-remover-web#1]
看过Web Audio API 实现的，效果没你这个好。ai-creator.top 图片处理的有计划开源么 。

**Comment by MartinDelophy** [comment]
> 看过Web Audio API 实现的，效果没你这个好。ai-creator.top 图片处理的有计划开源么 。

开放了 deoldify 老照片上色的最简代码 [老照片上色](https://github.com/MartinDelophy/deoldify-onnx-web)
