### ISSUE TITLE
How to get the vocal output?

### ISSUE THREAD

**Issue by Arvin-xc** [MartinDelophy/vocal-remover-web#3]
This application running on web is awesome! But it seems that it only can extract background music. How can I get the the vocal ouput? 🙏

**Comment by MartinDelophy** [comment]
will, the model i use it can only seperate the background music, when i subtract original music with background music, i find it not work。
but in this respository i find this work, maybe i need to dig it out from [this](https://github.com/seanghay/uvr-mdx-infer)

**Comment by MartinDelophy** [comment]
will, i fixed this problem, I thought that the part of the voice should be separated from the Fourier transform, but then I found that the part of the Mel spectrum could be processed
